---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest

dependencies:
#  python: requirements.txt
  galaxy: requirements.yml

#additional_build_files:
#  - src: files/ansible.cfg
#    dest: configs
#  - src: files/pip.conf
#    dest: configs
#  - src: files/hub-ca.crt
#    dest: configs
  # uncomment if custom RPM repositories are required
  #- src: files/custom.repo
  #  dest: configs

additional_build_steps:
  prepend_base:
    - ENV PKGMGR="/usr/bin/microdnf"
    # copy a custom pip.conf to override the location of the PyPI content
#    - ADD _build/configs/pip.conf /etc/pip.conf
    # remove the default UBI repository definition
    - RUN rm -f /etc/yum.repos.d/ubi.repo
    # copy the hub CA certificate and update the trust store
#    - ADD _build/configs/hub-ca.crt /etc/pki/ca-trust/source/anchors
#    - RUN update-ca-trust
    # if needed, uncomment to add a custom RPM repository configuration
    #- ADD _build/configs/custom.repo /etc/yum.repos.d/custom.repo

#  prepend_galaxy:
#    - ADD _build/configs/ansible.cfg ~/.ansible.cfg

...
