kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ee-minimal-rhel9
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest'
      importPolicy:
        scheduled: true
        importMode: PreserveOriginal
      referencePolicy:
        type: Source
