#SPDX-License-Identifier: MIT-0
---
# tasks file for aap-config

- name: Create a new token using controller username/password
  ansible.controller.token:
    description: 'Creating token to test controller jobs'
    scope: "write"
    state: present
    controller_host: "{{ aap_hostname }}"
    aap_username: "{{ aap_username }}"
    aap_password: "{{ aap_password }}"
  register: token

- name: Show token
  ansible.builtin.debug:
    msg: "{{ token }}"