apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aap
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    path: aap
    repoURL: https://github.com/nreilly-rhn/aap-setup
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-pipelines
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    path: pipelines
    repoURL: https://github.com/nreilly-rhn/aap-setup
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true