apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: aap-configuration
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    path: aap/aap-configuration
    repoURL: https://github.com/nreilly-rhn/aap-setup
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true